version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pr-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_review
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pr-manager-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      HTTP_ADDR: ${HTTP_ADDR}
      DB_URL: ${DB_URL}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      USER_TOKEN: ${USER_TOKEN}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
    ports:
      - "${APP_PORT:-8080}:8080"

  linter:
    image: golangci/golangci-lint:latest
    container_name: pr-manager-linter
    volumes:
      - .:/app
    working_dir: /app
    command: golangci-lint run -v --timeout=5m ./...



volumes:
  db-data: